### ISSUE TITLE
CentOS上编译报错

### ISSUE THREAD

**Issue by yanghg-basefx** [libpinyin/libpinyin#100]
我试图在CentOS7.2上自己编译libpinyin，但是报错：

```
没有规则可以创建 "data/gb_char.bin"需要的目标 "data/table.conf"。 停止
```

看起来是缺少table.conf，但是我确实没找到这个文件，也不知道去哪找，请问我是还缺少什么库吗？

**Comment by epico** [comment]
请问您用的是 libpinyin 哪个版本？

**Comment by yanghg-basefx** [comment]
@epico 就是从这个repo clone下来的

**Comment by yanghg-basefx** [comment]
@epico 好像解决了，用`./autogen.sh`配置的可以编译，`cmake`不行。如果不打算支持`cmake`的划建议把`CMakeLists.txt`删除，容易造成误会……

**Comment by epico** [comment]
其实用 autogen.sh 将数据下载后， cmake 就可以用了。

我对 cmake 不熟悉，cmake 更新会有滞后。

**Comment by yanghg-basefx** [comment]
多谢。我把issue关了。
