### ISSUE TITLE
构建问题

### ISSUE THREAD

**Issue by xukai2025** [libpinyin/libpinyin#101]
`
checking for memset... yes
checking for setlocale... yes
checking for string.h... (cached) yes
checking db.h usability... no
checking db.h presence... no
checking for db.h... no
configure: error: Cannot find Berkeley DB library version 4
yqxk@yqxk-virtual-machine:~/work/libpinyin-master$ 

`
小白不太会编译安装步骤
感谢大佬帮忙分析
[config.log](https://github.com/libpinyin/libpinyin/files/3102970/config.log)

**Comment by xukai2025** [comment]
ubuntu版本 16.04LTS
ibus版本1.5.11
Berkeley DB 这个已经安装了18.1.32
是不是库的链接问题

**Comment by xukai2025** [comment]
跪谢指点

**Comment by epico** [comment]
请安装 Berkeley DB 4.x/5.x 的 C 语言版本。
