### ISSUE TITLE
不同构建的包，有文件存在差异

### ISSUE THREAD

**Issue by yanghua4548** [libpinyin/libpinyin#102]
libpinyin-data有两个文件在不同的构建结果之间存在差异：
pinyin_index.bin
addon_pinyin_index.bin

通过调查发现是结构体PinyinIndexItem2因为字节对齐的原因导致某些情况下会有未初始化的内存被使用。
template<size_t phrase_length>
struct PinyinIndexItem2{
    phrase_token_t m_token;
    ChewingKey m_keys[phrase_length];

public:
    PinyinIndexItem2<phrase_length> () {
        memset(m_keys, 0, sizeof(ChewingKey) * phrase_length);
        m_token = null_token;
    }

   PinyinIndexItem2<phrase_length> (const ChewingKey * keys,
                                     phrase_token_t token) {
        memmove(m_keys, keys, sizeof(ChewingKey) * phrase_length);
        m_token = token;
    }
};
在我编译过程中，编译器采用了4字节对齐，所以当phrase_length值为单数时，虽然对所有成员变量进行了初始化，但因为字节对齐的原因，结构体大小会比所有成员变量内存大小之和要多出两个字节。这两个字节的内存并没有进行初始化，但依然会被使用到。
我对此进行了一些修改
diff --git a/src/storage/pinyin_phrase3.h b/src/storage/pinyin_phrase3.h
index d2e75ad..acd0b26 100644
--- a/src/storage/pinyin_phrase3.h
+++ b/src/storage/pinyin_phrase3.h
@@ -184,12 +184,13 @@ struct PinyinIndexItem2{
 
 public:
     PinyinIndexItem2<phrase_length> () {
\-        memset(m_keys, 0, sizeof(ChewingKey) * phrase_length);
\+        memset(this, 0, sizeof(*this));
         m_token = null_token;
     }
      PinyinIndexItem2<phrase_length> (const ChewingKey * keys,
                                      phrase_token_t token) {
\+        memset(this, 0, sizeof(*this));
         memmove(m_keys, keys, sizeof(ChewingKey) * phrase_length);
         m_token = token;
     }
这样是否可行，会有什么影响吗

**Comment by epico** [comment]
在这里可能问题不大。

但是如果 PinyinIndexItem2 是 class 并且有虚函数的话，就会有问题。

个人不推荐使用 memset(this, 0, sizeof(*this)) 这种写法...

**Comment by yanghua4548** [comment]
谢谢你的答复
请问，你有什么好的建议吗。我实在不能想到其他更好的办法

**Comment by epico** [comment]
```
const length = (phrase_length + 1) >> 1 << 1;
ChewingKey m_keys[length];
```

为了解决这个问题，可能会让代码更复杂...

**Comment by yanghua4548** [comment]
谢谢你的帮助 @epico

**Comment by epico** [comment]
不客气

**Comment by epico** [comment]
问一下，现在这个问题还存在吗？

**Comment by epico** [comment]
没有回复，关闭问题。
