### ISSUE TITLE
fatal error: config.h: No such file or directory

### ISSUE THREAD

**Issue by moc32** [libpinyin/libpinyin#104]
Hello, 
I am trying to build the library but I could not find the following include file:

libpinyin/src/include/memory_chunk.h:24:20: fatal error: config.h: No such file or directory
 #include "config.h"

Where can I find this file?
Best regards,
Moctar

**Comment by epico** [comment]
See https://github.com/libpinyin/ibus-libpinyin/wiki/Installation .

**Comment by moc32** [comment]
I am trying to cross-compile the library using code composer from the source code. Indeed when I download the package from sourceforge, I get the configure script which generates the config.h

**Comment by PureTryOut** [comment]
@moc32 note that this has been fixed since https://github.com/libpinyin/libpinyin/commit/a6d51d2f7c513393e92105290f488ee3bb4930e8 and you can now use CMake to build the project.
