### ISSUE TITLE
Cannot input 為 character

### ISSUE THREAD

**Issue by mawis** [libpinyin/libpinyin#105]
Unicode has two code points assigned for traditional variant of the 为 character:
U+70BA 為 and U+7232 爲

When I type "wei" using libpinyin and fcitx I can find the character 爲 but I never get presented the 為 character. How can I access this alternate character of the Hanzi?

System setup
-----------------

NixOS 19.09
libpinyin 2.3.0
fcitx 4.2.9.6
fcitx-engines.libpinyin 0.5.3

NixOS IME configuration:

```
  i18n = {
    consoleFont = "Lat2-Terminus16";
    consoleKeyMap = "de";
    defaultLocale = "zh_TW.UTF-8";
    inputMethod = {
      enabled = "fcitx";
      fcitx.engines = with pkgs.fcitx-engines; [ libpinyin rime ];
    };
  };
```

**Comment by Titubery** [comment]
I can find both 為 and 爲 in libpinyin. You may turn over more pages to find that.

**Comment by mawis** [comment]
Thanks. I will recheck. I though I paged through all characters, maybe I have overseen something.

**Comment by hexakon** [comment]
In case anyone else is encountering this issue, your input framework (e.g. Ibus) might've just included an outdated version. Downloading the release tarball from this repo and installing it might have fixed it for me -- but I also reinstalled a bunch of other input-related packages so I'm not 100% sure which one did the trick.
