### ISSUE TITLE
请将以下缺少的字词加入词库

### ISSUE THREAD

**Issue by hillwoodroc** [libpinyin/libpinyin#107]
撸 lu
𤆵 pa
𤆵耳朵 pa er duo

**Comment by epico** [comment]
"撸" 这个字在 gbk_char.table， 排列的比较靠后。

**Comment by hillwoodroc** [comment]
我翻了18页终于找到了。这是个现在很常用的字，怕是需要调整一下词频吧。

**Comment by epico** [comment]
是的，谢谢提醒，也许应该放入 gb_char.table .

**Comment by suokunlong** [comment]
还有一个字需要调整，我就不另外开ticket了：
质 zhi

我是在输入“质控”时发现的，死活找不到“质”，只能输入“质量”，“控制”，然后各删掉一个来拼凑。可以顺便把“指控”加入新词。

**Comment by hillwoodroc** [comment]
> 还有一个字需要调整，我就不另外开ticket了：
> 质 zhi
> 
> 我是在输入“质控”时发现的，死活找不到“质”，只能输入“质量”，“控制”，然后各删掉一个来拼凑。可以顺便把“质控”加入新词。

我在第二页就看到“质”了。

**Comment by suokunlong** [comment]
好吧，可能是我眼花了🌸

**Comment by suokunlong** [comment]
无法输入以下字词：
mai 唛
mai'tou 唛头

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin .

**Comment by epico** [comment]
ibus-libpinyin 1.11.93 is released.
