### ISSUE TITLE
Can libpinyin use the expanded pinyin dictionary

### ISSUE THREAD

**Issue by jacknlliu** [libpinyin/libpinyin#110]
Can `libpinyin` use the expanded pinyin dictionary file `pybase.mb` and `pyphrase.mb` from `~/.config/fcitx/pinyin`?

### Reference
- [Fcitx使用搜狗词库与皮肤](https://www.cnblogs.com/luoshuitianyi/p/11669619.html)
- [Extend_pinyin_dictionary](https://wiki.archlinux.org/index.php/fcitx#Extend_pinyin_dictionary)

**Comment by orzogc** [comment]
You can import sougou pinyin dictionary in libpinyin configuration of fcitx.
![DeepinScreenshot_select-area_20200301210622](https://user-images.githubusercontent.com/6040599/75626222-c00c2c00-5c00-11ea-9cc0-aecece689e3e.png)

**Comment by jacknlliu** [comment]
@orzogc There seems to be a bug in this function. After adding a dictionary, it will appear that when switching from Chinese input method to English input method, the delay is very large.

**Comment by epico** [comment]
@jacknlliu Please report to fcitx-libpinyin project, as this feature is implemented in fcitx-libpinyin.
