### ISSUE TITLE
DictionaryTreeView cannot be found

### ISSUE THREAD

**Issue by rekado** [libpinyin/libpinyin#114]
When attempting to open the settings by running libexec/ibus-setup-libpinyin (via the Gnome control center) I see this error:

```
main2.py:66: DeprecationWarning: bind_textdomain_codeset() is deprecated
  gettext.bind_textdomain_codeset(DOMAINNAME, 'UTF-8')
Traceback (most recent call last):
  File "main2.py", line 543, in <module>
    main()
  File "main2.py", line 539, in main
    PreferencesDialog(name).run()
  File "main2.py", line 75, in __init__
    self.__builder.add_from_file("ibus-libpinyin-preferences.ui")
gi.repository.GLib.Error: gtk-builder-error-quark: ibus-libpinyin-preferences.ui:1830:1 Invalid object type 'DictionaryTreeView' (6)
```

I see with `strace` that `dicttreeview.py` is read.
(This is observed on Guix System; I'm maintaining ibus-libpinyin for Guix.)

**Comment by epico** [comment]
Could you try to use python3?

We recommend to use the following command line:
```
%configure --disable-static \
           --with-python=python3 \
           --disable-boost
```

**Comment by rekado** [comment]
We are already using Python3 and do not use boost.

**Comment by epico** [comment]
Could you run `python3 main2.py` in the code repo?

**Comment by epico** [comment]
Could you run the following command line?

```
cd /usr/share/ibus-libpinyin/setup/
python3 main2.py
```

**Comment by rekado** [comment]
That is essentially the command that the script executes and, as expected, it leads to the same error.

**Comment by epico** [comment]
Could you try to set the following environment variable?

```
export PYTHONPATH=.
```

**Comment by epico** [comment]
No response, close issue now.
