### ISSUE TITLE
libpinyin 2.3.0 compilation error

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/libpinyin#115]
/usr/bin/ld: test_pinyin.o: undefined reference to symbol 'g_free'
/usr/bin/ld: /lib/x86_64-linux-gnu/libglib-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:446: test_pinyin] Error 1
make[3]: Leaving directory '/home/ryzenv/Downloads/libpinyin-master/tests'
make[2]: *** [Makefile:503: all-recursive] Error 1
make[2]: Leaving directory '/home/ryzenv/Downloads/libpinyin-master/tests'
make[1]: *** [Makefile:478: all-recursive] Error 1
make[1]: Leaving directory '/home/ryzenv/Downloads/libpinyin-master'
make: *** [Makefile:383: all] Error 2

**Comment by epico** [comment]
Could you try the latest code in git repo?

or try the following command line:
```
export LDFLAGS="-lglib"
```

**Comment by epico** [comment]
Maybe the following command line also helps:

```
export LDFLAGS=`pkg-config glib-2.0 --libs`
```

**Comment by ping-wu** [comment]
The second option " LDFLAGS=`pkg-config glib-2.0 --libs` " solved the problem.

**Comment by alx696** [comment]
> Maybe the following command line also helps:
> 
> ```
> export LDFLAGS=`pkg-config glib-2.0 --libs`
> ```

先执行 `export LDFLAGS=`pkg-config glib-2.0 --libs` , 再执行 `./autogen.sh --prefix=/usr` 这样在make时不会出现g_free错误.
> 只在make前执行是不能解决问题的... 谢谢.
