### ISSUE TITLE
ibus的libpinyin，如何导入词库？

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/libpinyin#116]
(re-posted from the Ubuntu Chinese Forum)

由 男菜鸟 » 2020-08-11 22:28
ibus的libpinyin在UBT20.04版本开始很好用了。但是如何导入词组？我根据在，中文/首选项/用户数据/帮助 的介绍，做了一个txt文件试验，
如:
松榆里 song'yu'li
王斯庆 wang'si'qing
.....

把上述文件“导入”后，重启系统，在中文系统下，输入"syl","wsq".并不能输出"松榆里"、"王斯庆"，而是必须全拼输入一次“songyuli”、“wangsiqing” 逐一确认松、榆、里；王、斯、庆 后，才能在以后只需输入 "syl","wsq"，就能输出"松榆里"、"王斯庆"! 那这实际上就是"将每个输入记录为新词"，而不是批量输入了？如何可以批量输入词组？

original post appeared in:

https://forum.ubuntu.com.cn/viewtopic.php?f=8&t=491421

**Comment by epico** [comment]
请先删除 ~/.cache/ibus/libpinyin/user.conf 文件，重启。

再次导入词组，直接就可以使用了，请等待 10 分钟后再重启或者注销...

**Comment by ping-wu** [comment]
我试了一下，第一个词没有问题，但第二个词就打不出来了。

**Comment by epico** [comment]
我这里  "松榆里" 和 "王斯庆" 工作正常啊！
