### ISSUE TITLE
Assertion fail when use libzhuyin with zhuyin_get_zhuyin_offset with ' separator in string

### ISSUE THREAD

**Issue by wengxt** [libpinyin/libpinyin#117]
When setup like this: 
zhuyin_set_full_pinyin_scheme (HANYU)
zhuyin_parse_more_full_pinyins("ao\'")
zhuyin_guess_sentence()
zhuyin_get_zhuyin_offset(3)

=> zhuyin.cpp:1451：bool _check_offset(pinyin::PhoneticKeyMatrix&, size_t): 假设 ‘zero_key != key’ 失败。

**Comment by epico** [comment]
Could you provide a small test case file for this issue?

**Comment by wengxt** [comment]
```
#include <zhuyin.h>
#include <iostream>

using namespace std;

int main() {
    auto c = zhuyin_init("/usr/lib/ibus-libzhuyin/data/", "/Invalid/PATH");
    zhuyin_set_options(c, USE_TONE | ZHUYIN_CORRECT_ALL);
    zhuyin_set_full_pinyin_scheme(c, FULL_PINYIN_HANYU);
    auto i = zhuyin_alloc_instance(c);
    zhuyin_parse_more_full_pinyins(i, "ao'");
    zhuyin_guess_sentence(i);
    char* s;
    zhuyin_get_sentence(i, &s);
    std::cout << s << std::endl;
    std::cout << zhuyin_get_parsed_input_length(i) << std::endl;
    size_t offset;
    zhuyin_get_zhuyin_offset(i, 3, &offset);
    std::cout << offset << std::endl;
    return 0;
}
```

```
$ g++ -g -O0 -std=c++17 1.cc `pkg-config --cflags libzhuyin`  `pkg-config --libs libzhuyin`; ./a.out 
open /Invalid/PATH/user.conf failed.奧
3
a.out: zhuyin.cpp:1451: bool _check_offset(pinyin::PhoneticKeyMatrix&, size_t): Assertion `zero_key != key' failed.
```

**Comment by wengxt** [comment]
"ni'hao" and get offset at 5 can also trigger this.

**Comment by epico** [comment]
I think Traditional Chinese may not use the symbol ' .

**Comment by wengxt** [comment]
@epico I set the scheme to hanyu piniyn and I'm using parse_full_pinyin. I think it's pretty legit to support ' separator when hanyu pinyin is used. Otherwise under zhuyin style of typing, it's not possible to force things like xi'an.

**Comment by epico** [comment]
Normally Traditional Chinese users will input tone I guess.

**Comment by wengxt** [comment]
@epico I doubt if they use hanyu pinyin at all.. but then can you make ' to be something like zero tone for pinyin? I guess that might be a easier change to make.

**Comment by epico** [comment]
I think the current zhuyin.cpp code doesn't expect the ' in the input string.

And ibus-libzhuyin will filter out the ' symbol.

**Comment by epico** [comment]
Could you test the following patch?

https://pwu.fedorapeople.org/ibus/libpinyin/libpinyin-post.patch

**Comment by wengxt** [comment]
@epico I think zhuyin_get_right_zhuyin_offset also needs some change.

**Comment by epico** [comment]
Could you test the following patch again?

https://pwu.fedorapeople.org/ibus/libpinyin/libpinyin-post.patch

**Comment by epico** [comment]
The above patch is updated for zhuyin_get_right_zhuyin_offset function.

**Comment by epico** [comment]
Fixed in https://github.com/epico/libpinyin .
