### ISSUE TITLE
Segmentation fault on x86

### ISSUE THREAD

**Issue by PureTryOut** [libpinyin/libpinyin#120]
For some reason libpinyin segfaults constantly on the x86 architecture (note, the 32-bit one, not amd64 or x86_64).

```
rm -f phrase_index.bin pinyin_index.bin addon_phrase_index.bin addon_pinyin_index.bin bigram.db gb_char.bin gbk_char.bin opengram.bin merged.bin art.bin culture.bin economy.bin geology.bin history.bin life.bin nature.bin people.bin science.bin society.bin sport.bin technology.bin
../utils/storage/gen_binary_files --table-dir ../data
make[2]: *** [Makefile:542: bigram.db] Segmentation fault (core dumped)
```

This happens on Alpine Linux with GCC 9.3.0.

**Comment by PureTryOut** [comment]
Note that this is using the last release, 2.3.0. It seems that is quite old and there have been a lot of commits since, so just having a newer release might help here.

**Comment by epico** [comment]
Okay, I will release new libpinyin later.

**Comment by PureTryOut** [comment]
Actually I tested the latest master for this issue in the meantime, it does not resolve it :cry: 

I've been trying to build it with Ninja rather than Make (as Make seems to be the one segfaulting), but that doesn't succeed because of #123.

**Comment by epico** [comment]
Sorry, I think CMake is not maintained as well as autoconf...

**Comment by epico** [comment]
I think I tried with `make -j8`, it seems passed compiling...

**Comment by epico** [comment]
Which DBM are you using, Berkeley DB or Kyoto Cabinet?

**Comment by PureTryOut** [comment]
Berkeley DB

**Comment by epico** [comment]
libpinyin 2.4.91 is released.

**Comment by PureTryOut** [comment]
Nice! However, that doesn't fix this issue sadly
https://gitlab.alpinelinux.org/PureTryOut/aports/-/jobs/193870

**Comment by epico** [comment]
Could you try autoconf with tar ball?

Sometimes CMake is not updated...

**Comment by PureTryOut** [comment]
I'm downloading the tarball straight from Github so that doesn't make sense, it is just the git tag you made which is a snapshot of git master at that point in time, but sure I gave it a shot. No luck though.

https://gitlab.alpinelinux.org/PureTryOut/aports/-/jobs/194377

**Comment by epico** [comment]
Sorry, I mean there is one tar ball containing data files to download.

URL:
https://github.com/libpinyin/libpinyin/releases/tag/2.4.91
https://github.com/libpinyin/libpinyin/releases/download/2.4.91/libpinyin-2.4.91.tar.gz

**Comment by PureTryOut** [comment]
Doesn't seem to be the case. Well or the autotools ignore the existing data files, because they try to download them anyway using that tarball.

**Comment by PureTryOut** [comment]
Using that tarball doesn't make a difference sadly

https://gitlab.alpinelinux.org/PureTryOut/aports/-/jobs/194428

Although it is convenient to not seperately having to download the models anymore, thanks!

**Comment by epico** [comment]
Could you try to build libpinyin with Kyoto Cabinet?

**Comment by PureTryOut** [comment]
That does seem to make it work yes. However, that is available on less architectures, at least on Alpine Linux, than BerkeleyDB is and I rather don't use it. Especially armv7 will be left out which most definitely do not want to miss.

Also, the release tarball doesn't actually include CMake files, could those be added?

**Comment by epico** [comment]
Maybe it is an issue with Berkeley DB...

Sorry, the tar ball is created with autoconf, not include CMake files.

**Comment by epico** [comment]
libpinyin 2.4.92 is released, could you try with Berkeley DB again?

**Comment by PureTryOut** [comment]
[Same as before](https://gitlab.alpinelinux.org/PureTryOut/aports/-/jobs/233080).

That CI job is building libpinyin 2.4.92 with autotools from the release tarball on SourceForge.

**Comment by epico** [comment]
Does this still happen with libpinyin 2.6.0 tar ball?

**Comment by PureTryOut** [comment]
Oh uh, I seem to have enabled x86 quite a while ago so I guess it doesn't :shrug: 
Closing for now, I can always re-enable it later.
