### ISSUE TITLE
光标在句中，修改光标后的候选字词后，有时会将光标之前的词一起修改了

### ISSUE THREAD

**Issue by nagae-memooff** [libpinyin/libpinyin#125]
标题可能不太明确，这个问题是这样的。
原issue提在这里： https://github.com/libpinyin/ibus-libpinyin/issues/269

比如我在输入了一系列拼音时，候选词的大部分都符合我的预期，但唯独最后的几个字或词不符合。在这种状态下，我会使用ctrl+←回退光标，以便保持前面的猜测，只修改最后几个字。

比如，我希望输入"buzhidaoweishenmezucifuxianbuchulai(不知道为什么组词复现不出来)"， 输入法猜测为： “不知道为什么组词赋闲不出来”，如图1。这种情况下，如图2，我会使用ctrl+←将光标移到“fuxian”前，按6选择“复现”。然而，“复现”定词以后，光标之前的、原本符合预期的“组词”却也跟着变成了“祖祠”，如图3.也即，定词会导致光标之前的词语也变换了猜测结果。

这种情况还有另一种更难受的变体，如果我修改的是最后一个字/词，触发了这种情况，那么输入框消失，整句落地到输入框里以后，光标修改的位置之前的词，也被意外修改了。这种情况下不仅要重新输入，并且错误的句子还会被记录为用户词库，对后续输入也产生影响。

概率不是很高，比较难以定向复现。

版本：
ibus-libpinyin 1.11.92 (源代码编译)
libpinyin: 2.3.0 （源代码编译）
ibus 1.5.11 (ubuntu 16.04 官方源)

![image](https://user-images.githubusercontent.com/4215831/90849020-e5544880-e3a0-11ea-8fef-65533e12db07.png)
![image](https://user-images.githubusercontent.com/4215831/90849046-f1d8a100-e3a0-11ea-89a7-0e3eb3680add.png)
![image](https://user-images.githubusercontent.com/4215831/90849069-fe5cf980-e3a0-11ea-80ba-82f335901dd1.png)

**Comment by epico** [comment]
Let us continue to discuss this issue in the previous issue, closed as duplicated.
