### ISSUE TITLE
CMake: tests don't run with out-of-source builds

### ISSUE THREAD

**Issue by PureTryOut** [libpinyin/libpinyin#126]
Linux distributions tend to prefer to build things out of the source directory nowadays, normally in a directory called something like `build`. With CMake this can be achieved by running `cmake -B <directory to build it in>`, e.g. `cmake -B build`.

For just compiling libpinyin, this works fine. However, this makes the tests fail:

```
Test project /home/bart/Documents/Git/alpine/aports/testing/libpinyin/src/libpinyin-89972e4d34331fe199633b10408f0656f7361e32/build
    Start 1: pinyin
1/3 Test #1: pinyin ...........................***Exception: SegFault  0.01 sec
open ../data/table.conf failed.
load ../data/table.conf failed!

    Start 2: phrase
2/3 Test #2: phrase ...........................***Exception: SegFault  0.01 sec
open ../data/table.conf failed.
load ../data/table.conf failed!

    Start 3: chewing
3/3 Test #3: chewing ..........................***Exception: SegFault  0.00 sec
open ../data/table.conf failed.
load ../data/table.conf failed!


0% tests passed, 3 tests failed out of 3

Total Test time (real) =   0.02 sec

The following tests FAILED:
          1 - pinyin (SEGFAULT)
          2 - phrase (SEGFAULT)
          3 - chewing (SEGFAULT)
```

The problem seems to be that those tests expect the data to be in a specific directory, but when building out-of-source this directory is not in the same place relative to where you're building.

https://github.com/libpinyin/libpinyin/blob/master/tests/test_chewing.cpp#L33

I'm not sure how to properly fix this, I guess some defines have to be used that get filled by CMake?

**Comment by epico** [comment]
I think table.conf needs to be copied from ${CMAKE_SOURCE_DIR}/data/ to ${CMAKE_BINARY_DIR}/data/ .

**Comment by PureTryOut** [comment]
Since those tests got disabled in #127 anyway, this is not an issue anymore.
