### ISSUE TITLE
CMake: tests hang indefinitely

### ISSUE THREAD

**Issue by PureTryOut** [libpinyin/libpinyin#127]
Now tests can be ran with CMake since 91121b958219e022d3e3f8f55ee1dd14a42113a5 and if you run the tests in the source directory to workaround #126, they never actually succeed but hang indefinitely. Looking into the tests, they all seem to use some loop which I guess just never finishes?

**Comment by epico** [comment]
The three tests are interactive tests.

Without manual input, it will not exit.

**Comment by epico** [comment]
Fixed in https://github.com/epico/libpinyin .

**Comment by PureTryOut** [comment]
Ah that explains things. Works, thanks!
