### ISSUE TITLE
libzhuyin failed to expose `zhuyin_get_zhuyin_key_rest`

### ISSUE THREAD

**Issue by Brli** [libpinyin/libpinyin#129]
git master branch compiled with `autogen.sh --enable-libzhuyin` under Arch Linux.

and check with `objdump -T src/.libs/libzhuyin.so | grep 'zhuyin_get_zhuyin_key_rest'`

it doesn't return the function name, but only the `*_length` and `*_positions` ones.

**Comment by ryuanlu** [comment]
https://github.com/libpinyin/libpinyin/pull/130#issue-478643885

**Comment by epico** [comment]
Thanks for the report!

The issue is fixed now.
