### ISSUE TITLE
configure.ac:128: error: required file 'data/table.conf.in' not found

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/libpinyin#134]
Got this error:

"configure.ac:128: error: required file 'data/table.conf.in' not found"

when trying to compile libpinyin 2.4.92 in Ubuntu 20.04 LTS

**Comment by epico** [comment]
Fixed in https://github.com/libpinyin/libpinyin/ .

**Comment by ping-wu** [comment]
configure: error: Cannot find Berkeley DB library version 4

the version of berkeley database in Ubuntu 20.04 is 5.3; i have no intention of downgrading it just to compile libpinyin

**Comment by epico** [comment]
Please install libdb-dev package, libpinyin compiles with Berkeley DB 5.

**Comment by ping-wu** [comment]
was able to make a deb package, but it appears to be in conflict with the existing 2.3 version, won't install.  make install also failed.

**Comment by epico** [comment]
Please discuss with the Ubuntu community, thanks!

Also you can ask Ubuntu to update the libpinyin package version.
