### ISSUE TITLE
libpinyin-2.4.92 用 kyotocabinet 编译安装后 ibus-libpinyin 无候选项

### ISSUE THREAD

**Issue by tuberry** [libpinyin/libpinyin#135]
以 --with-dbm=BerkeleyDB 编译能正常使用。不确定和依赖版本是否有关。

**Comment by epico** [comment]
请删除 ~/.cache/ibus/libpinyin/user.conf 文件试试。

**Comment by tuberry** [comment]
经尝试后依旧。你那边无法复现的话应该不是代码的问题。
