### ISSUE TITLE
Segfault in CMake Release build due to assert with side effects

### ISSUE THREAD

**Issue by jingyu9575** [libpinyin/libpinyin#143]
I've tried to build this project in MSYS2/Windows with CMake. The Debug build works but the Release build of `test_pinyin` crashes.

There are several instances of `assert` with side effects, e.g.:

https://github.com/libpinyin/libpinyin/blob/76a20ae5801f6002d08fd698d06f447cae112d6f/src/lookup/phonetic_lookup.h#L763-L766
	
By default `assert` is removed in the Release build so `cur_constraint == NULL`.

Should I enable `assert` in the Release build? How do I do it in CMake command line?

**Comment by epico** [comment]
Sorry, I think currently please enable assert in the Release build.

Here are some information for CMake.
URL: https://gitlab.kitware.com/cmake/cmake/-/issues/18249

Or try to use ./configure for compiling, which is maintained by me.

**Comment by jingyu9575** [comment]
Thanks, I've removed `-DNDEBUG` from `CMAKE_CXX_FLAGS_RELEASE` and `CMAKE_C_FLAGS_RELEASE` and the executable works.

**Comment by epico** [comment]
I just find some time to work on this issue, I think it is fixed now.
