### ISSUE TITLE
需求：补全快捷键到首选项

### ISSUE THREAD

**Issue by wsxy162** [libpinyin/libpinyin#148]
快捷键 Shift+U/I/V，在首选项的快捷键页中没有列出来。我不使用 Shitf+V 来输入英文，现在没有选项可以禁用掉它。
我知道输入法中尽管叫做中/英模式，但其实不是按输入中英文来区别的，而是 commit 进入的方向不同来区分。比如打字 commit 进拼音框（preedit）叫做中文模式，直接 commit 进程序叫英文模式。这是个历史习惯问题，如果不拘泥于中英文模式的叫法，把  V 模式合并进中文模式也不是不可以，很多成熟的商业中文输入法中也是这么处理。

**Comment by epico** [comment]
v 模式可以输入英文啊。

**Comment by wsxy162** [comment]
是的这个功能能用，我的原请求是把它缺少的快捷键设置补充到设置页上。UIV 模式在设置界面上不存在，只在用户按相应键后才知道它们的存在。
V 模式这个功能使用上也不方便，每个英文单词都要用 Shift+V 就很麻烦。因为这个 V 功能的存在还造成输入的不一致，比如其他字母使用 Shift+字母键，可以输出大写的字母，但唯独在 V 上就必须得按两次 V。

**Comment by epico** [comment]
请问您建议的英语输入行为是？

**Comment by wsxy162** [comment]
我更习惯于中英文混输，这是以前输入法带来的习惯。击入字母显示到 preedit 框里，如果向上屏的是中文，按空格键选第一个候选词上屏；如果想上屏的是英文，按回车键上屏英文。
说到英文上屏，这也与这个 issue 有关 #93 。

**Comment by epico** [comment]
好像现在就是这样实现的，只是不能显示原始输入而已。

**Comment by wsxy162** [comment]
单独的英文联想功能是有用的，但不应该做成按一次 Shift+V 输一个英文单词的形式。V 模式做成像简繁体切换的模式那样，在该模式下就可以持续的输入英文并使用英文联想功能了。当然这个 V 模式的快捷键不应该与常规输入 Shift+V 想上屏大写的 V 冲突。

这是我设想的输入模式，也是问题描述里提到的，原有的中/英文模式其实跟输入中英文没关系。

**Comment by wsxy162** [comment]
> 好像现在就是这样实现的，只是不能显示原始输入而已。

现在的进入 V 模式的方式会跟普通输入中打大写 V 冲突。

**Comment by epico** [comment]
英文联想功能，可以考虑试一试 ibus-typing-booster.

**Comment by wsxy162** [comment]
在 ibus-table 里对应中英文模式的是 table commit 和 direct commit。如果参考过来，libpinyin 应该是拼写模式和直输模式。这可能比原来的中英文模式设定更能安排功能。

**Comment by wsxy162** [comment]
我想最简单的对 V 模式的改动是把快捷键改成其他非字母键，就不会影响到常规打字了。比如设置成 Shift+：冒号。

**Comment by wsxy162** [comment]
在中文模式下打英文不能连贯使用 Shift 打大写字母，比如可以直接打 IBus，但不能直接打 openSUSE。
抱歉，才发现原来两个 ibus-pinyin 的 issue 都开错到这边。
