### ISSUE TITLE
请教一下有关拼音转中文的方案

### ISSUE THREAD

**Issue by sirodeneko** [libpinyin/libpinyin#156]
我想开发一个拼音（词或者句子）转中文的程序，我经过搜索后发现了这个库，但是这个库似乎是为输入法准备的，有非常复杂的功能，我尝试编译了一下，还是没编译成功。也许我应该稍微裁剪一下不必要的代码。如果我需要实现这么一个程序，我应该重点关注那一部分的代码呢，或者说有什么好的方案可以提供参考吗

**Comment by epico** [comment]
https://github.com/libpinyin/ibus-libpinyin/wiki/Installation
