### ISSUE TITLE
Plan for alternatives of Berkeley DB?

### ISSUE THREAD

**Issue by felixonmars** [libpinyin/libpinyin#44]
This is a feature request for some alternatives of berkeley db, as it's decided to be deprecated and may be dropped in the long term by Arch Linux.

**Comment by epico** [comment]
Draft code landed on https://github.com/epico/libpinyin .
Support to use Kyoto Cabinet now.

**Comment by felixonmars** [comment]
Thanks a lot! I'll try it.

**Comment by felixonmars** [comment]
Feature request: Would it be possible to have a migration tool, so users using bdb can safely migrate their config folder? Preferably with auto-detection etc, but a simple command line tool could be enough if that's too complicated.

Thanks!

**Comment by epico** [comment]
Could you open a new issue for RFE?

**Comment by felixonmars** [comment]
Opened as #51, closing this one. Thanks!
