### ISSUE TITLE
ibus-libpinyin怎么保存个人词库以便重装？

### ISSUE THREAD

**Issue by passchaos** [libpinyin/libpinyin#49]
libpinyin的默认词库太烂了，怎么才能保存自己的词库，将来重装系统后恢复词库？

**Comment by epico** [comment]
ibus-libpinyin 1.6.99.20150203 已发布，
请先打开 "将每个输入记录为新的词汇" 选项，
打开之后，输入的新短语即可通过 "导出" 功能导出。
