### ISSUE TITLE
fcitx-libpinyin relays on the binary tools of libpinyin.

### ISSUE THREAD

**Issue by wengxt** [libpinyin/libpinyin#50]
Hope it's not removed.

This would remove a feature from fcitx-libpinyin, thanks.

**Comment by 1dot75cm** [comment]
https://github.com/epico/libpinyin/issues/5#issuecomment-73201042
epico 说：
> 之前，fcitx-libpinyin 提供了繁体中文数据。
> 现在，libzhuyin 和 ibus-libzhuyin 已经发布，请使用 libzhuyin 的繁体中文数据。
> 为了方便调试 libpinyin，请使用 libpinyin 或 libzhuyin 自带的中文数据，谢谢。

**Comment by wengxt** [comment]
That's irrelavent. There's no guarantee that libzhuyin shares same data format as libpinyin. So even I'd like to use zhuyin's data, I will need to generate it with libpinyin's tool.

fcitx-libpinyin can use Traditional Chinese data with pinyin, not only for zhuyin.

**Comment by epico** [comment]
After discussed with Xuetian Weng, will temporarily restore libpinyin tools in the next release.

**Comment by epico** [comment]
libpinyin 1.1.0 restored the tools.
