### ISSUE TITLE
{Feature Request} BDB -> Kyoto Cabinet Migration Tool

### ISSUE THREAD

**Issue by felixonmars** [libpinyin/libpinyin#51]
(Splitted from #44)

Would it be possible to have a migration tool, so users using bdb can safely migrate their config folder? Preferably with auto-detection etc, but a simple command line tool could be enough if that's too complicated.

Thanks!

**Comment by epico** [comment]
Draft code is on https://pwu.fedorapeople.org/bdbtokyotodb/ .

BTW, not test it yet.

As the tools requires both DBM to compile, I won't merge it into libpinyin for now.
