### ISSUE TITLE
How to build the library

### ISSUE THREAD

**Issue by hykwok** [libpinyin/libpinyin#53]
I could use cmake to generate the Makefile but I could not build the source codes because the <config.h> was missing.
So, what's the requirement of this library? And how to build the library?
Thanks

**Comment by hykwok** [comment]
I found the solution from the wiki:
https://github.com/libpinyin/libpinyin/wiki/libpinyin-playground.
However, the command should be "./autogen.sh" rather than "./configure".

**Comment by epico** [comment]
Please use "./autogen.sh", the autotool is the default build system. :)
