### ISSUE TITLE
自然码模式中无法输入单韵母字符

### ISSUE THREAD

**Issue by zhouxiaobo500** [libpinyin/libpinyin#55]
如：爱（ai）、呃（ee）、昂（ah）、嗯（en）等等。
而sunpinyin输入以上内容均正常。

难道有别的输入单韵母方式吗？

**Comment by epico** [comment]
Fixed in https://github.com/epico/libpinyin/commit/6783bac98e70b14f1c58de63a9dcc9fce919d78c .

**Comment by zhouxiaobo500** [comment]
还是没有好ei（打不出来ei）。。

**Comment by epico** [comment]
这个功能需要 libpinyin 1.2.91 和 上边的 patch ...

**Comment by zhouxiaobo500** [comment]
诶，所以说是解决不了了？

**Comment by epico** [comment]
需要 libpinyin 1.2.91 或者更高的版本。

**Comment by epico** [comment]
As libpinyin 1.3.0 is released, close issue.

**Comment by zhouxiaobo500** [comment]
thx!
