### ISSUE TITLE
是否有计划加入对形码的支持？

### ISSUE THREAD

**Issue by zhouxiaobo500** [libpinyin/libpinyin#56]
fcitx内置的自然码中包含了对形码的支持，而内置输入法又缺乏对于外置词库的拓展。
libpinyin能否借鉴fcitx加入对该功能？

**Comment by epico** [comment]
请问自然码的形码指的是？

**Comment by zhouxiaobo500** [comment]
@epico 可以参考官网：http://www.zrm.com.cn/uiysuomy.htm
fcitx用的是一个zrm.mb的码表文件用作定义。

**Comment by epico** [comment]
谢谢提供文档。

猜测自然码的声形码是通过将单个汉字拆成两部分，通过输入相应部分的声母实现的？

**Comment by zhouxiaobo500** [comment]
是的，官方给出的拆字方案较为复杂。
能否将码表文件打开并用作分析？

**Comment by epico** [comment]
要是我没有记错的话，自然码的声形码是有专利的...

**Comment by zhouxiaobo500** [comment]
作为第三方平台，fcitx已经做出第一步了。
如果实在担心版权问题，可以尝试联系自然码的创始人周志农。。

**Comment by epico** [comment]
没有联系方式...

另外，如果是码表的话，请使用 ibus-table 项目。

**Comment by zhouxiaobo500** [comment]
非常感谢提供的链接！但好像没法使用？
没有ibus-table-createdb命令。

**Comment by epico** [comment]
ibus-table-createdb 在 ibus-table 的包中。
