### ISSUE TITLE
有联想功能吗

### ISSUE THREAD

**Issue by fanple** [libpinyin/libpinyin#57]
比如输入“中”后，能联想到“中国”，“中间”... ...

这个功能libpinyin是否支持或有计划实现这个功能？

**Comment by epico** [comment]
libpinyin 已经初步支持, ibus-libpinyin 不支持...

联想功能的相关函数:
pinyin_guess_predicted_candidates
pinyin_choose_predicted_candidate

**Comment by ping-wu** [comment]
联想功能支持了没？

**Comment by epico** [comment]
libpinyin 支持联想功能，在输入 "开始" 后，可能联想到 "了" 等。

参见：
pinyin_guess_predicted_candidates
pinyin_choose_predicted_candidate

ibus-libpinyin 还不支持。

**Comment by epico** [comment]
ibus-libpinyin 1.11.93 已经初步支持。
