### ISSUE TITLE
libpinyin 的词库能推倒重来过吗？

### ISSUE THREAD

**Issue by hillwoodroc** [libpinyin/libpinyin#59]
当真是很多常用词都打不出来，远不如已经停止开发的 sunpinyin 和 ibus-pinyin，真是严重影响输入效率，目测已经不是小修小补能解决的。

**Comment by epico** [comment]
请自行导入词库...

或者有符合 GPL 或 CC 协议的词库，我可以合并。

要是我没记错的话，ibus-pinyin 的词库是将词汇的所有可能发音都标注出来...

**Comment by hillwoodroc** [comment]
举个例子，“立马“这个常用词组，在 ibus-pinyin, sunpinyin, rime 都是能够打出来的，只有 libpinyin 不行，这显然不是是否发发音全部标出来的问题了，而是词库里面缺少这个词组。这样的情况太多了，没办法一一举例了。
libpinyin 是 ibus-pinyin 和 sunpinyin 的融合，算法应该是融合了，但是词库没有融合。ibus-pinyin 和 sunpinyin 词库的授权协议应该是没问题至少是兼容 GPL 的，我一直都觉得用这两个词库都比现在的好，我建议把这两个词库拿来用作基础词库。

**Comment by epico** [comment]
这个问题我考虑一下。

ibus-pinyin 和 rime 的词库好像是没有拼音的，碰到多音字，会标注所有的拼音的。
sunpinyin 的词库协议是 Apache License Version 2.0。

**Comment by edsgerlin** [comment]
我看到libpinyin的license是GPLv2+，那么不如把其升级至GPLv3+，这样就能与Apache 2.0兼容了。之后只要用sunpinyin词库即可。

**Comment by epico** [comment]
谢谢建议，目前的 libpinyin 1.7 开发计划如下:
1. 升级 License 到 GPLv3+
2. 去除 libpinyin 中的拼音音调
3. 导入 sunpinyin 的词典

为了兼容性，打算仅仅导入缺失的词汇。

**Comment by edsgerlin** [comment]
很高兴看到这个项目有人用心维护，因为反感fcitx所以一直没有用rime(与ibus兼容性不太好)，ibus-libpinyin是当前ibus下最好用的了。
感谢epico！

**Comment by epico** [comment]
open-gram 词典已导入 libpinyin 1.6.91, 关闭 issue.

URL: https://github.com/sunpinyin/open-gram/
