### ISSUE TITLE
双拼小鹤方案“ao“的输入存在问题

### ISSUE THREAD

**Issue by Novite5** [libpinyin/libpinyin#60]
小鹤应该是直接键入字母 "a" + "o",但 libpinyin 中需要按零声母处理，键入 "o" + "c".

**Comment by epico** [comment]
这个问题我回来看一下。

记录下小鹤拼音的网址: http://www.flypy.com/pin.html

**Comment by epico** [comment]
Attempt to fix it in:

https://github.com/epico/libpinyin/commit/88c6d1ac5b6a945730554da7a22e2e7716055bcb

**Comment by epico** [comment]
As lipinyin 1.5.91 and ibus-libpinyin 1.7.91 are released, close issue.
