### ISSUE TITLE
pinyin_get_right_pinyin_offset doesn't give correct result for separator

### ISSUE THREAD

**Issue by wengxt** [libpinyin/libpinyin#61]
when input is n'a, idx will be 3 for  pinyin_get_right_pinyin_offset(inst, 0, &idx) .

**Comment by epico** [comment]
Fixed in https://github.com/epico/libpinyin/commit/bfe12876720e38a720169ef49a575e2f010a3579 .

**Comment by epico** [comment]
As libpinyin 1.5.92 is released, close issue.
