### ISSUE TITLE
pinyin_remember_user_input may abort on certain non-chinese string.

### ISSUE THREAD

**Issue by wengxt** [libpinyin/libpinyin#62]
Please make it fail silently in such case.

**Comment by epico** [comment]
The pinyin_remember_user_input function only accepts Chinese characters.

I prefer not to fix this issue now, as you already work around it.

**Comment by wengxt** [comment]
Well obviously no, cloudpinyin may return arbitrary unicode character (if they do support emoji or sth).

I mean, isn't it very easy to handle the failure right here? I don't think it's too complex to fix it.
https://github.com/libpinyin/libpinyin/blob/c931de493502be9ac334ae9ab3be96649017f8be/src/pinyin.cpp#L2877

**Comment by epico** [comment]
Sorry, I forget the emoji unicode.

Fixed in https://github.com/epico/libpinyin/commit/eb08ebb49b4823b17c749cde377c0aa1c6fe76ea .

Please review it, thanks!

**Comment by epico** [comment]
As libpinyin 1.5.92 is released, close issue.
