### ISSUE TITLE
make install issue with libpinyin

### ISSUE THREAD

**Issue by primohan01** [libpinyin/libpinyin#64]
Hi,

I was able to successfully build this application but getting below error durint make install.
[  2%] Building CXX object src/lookup/CMakeFiles/lookup.dir/pinyin_lookup2.cpp.o
In file included from /home/mohankhanzode/Downloads/libpinyin-master/src/storage/chewing_large_table2.h:25:0,
                 from /home/mohankhanzode/Downloads/libpinyin-master/src/storage/facade_chewing_table2.h:25,
                 from /home/mohankhanzode/Downloads/libpinyin-master/src/lookup/pinyin_lookup2.cpp:22:
/home/mohankhanzode/Downloads/libpinyin-master/src/include/memory_chunk.h:24:20: fatal error: config.h: No such file or directory
 #include <config.h>
                    ^
compilation terminated.
make[2]: *** [src/lookup/CMakeFiles/lookup.dir/pinyin_lookup2.cpp.o] Error 1
make[1]: *** [src/lookup/CMakeFiles/lookup.dir/all] Error 2

I have commented config.h files in other files and didn't observe this error but now getting other errors.

[logs.txt](https://github.com/libpinyin/libpinyin/files/585204/logs.txt)

**Comment by epico** [comment]
Please use autoconf instead, cmake files are out of date.

https://github.com/libpinyin/ibus-libpinyin/wiki/Installation

**Comment by epico** [comment]
Updated cmake files in https://github.com/epico/libpinyin .

**Comment by epico** [comment]
As libpinyin 1.7.0 is released, close issue.
