### ISSUE TITLE
table.conf

### ISSUE THREAD

**Issue by calucita** [libpinyin/libpinyin#67]
Hello there, 

I've been trying to compile the library but the file data/table.conf does not exist and the build crashes... 

Any suggestions?

**Comment by epico** [comment]
If I remember correctly, libpinyin will download  model14.text.tar.gz automatically.

If not, please download and extract files from:
https://sourceforge.net/projects/libpinyin/files/models/model14.text.tar.gz

**Comment by epico** [comment]
Close issue.
