### ISSUE TITLE
Build fail on Ubuntu 16.04

### ISSUE THREAD

**Issue by Novite5** [libpinyin/libpinyin#68]
libpinyin-1.7.0
`AX_CXX_COMPILE_STDCXX([11])`in ./configure.ac reported syntax error.
comment this line fix the problem.

**Comment by epico** [comment]
Please try to install autoconf-archive package.

**Comment by Novite5** [comment]
This package has already been installed.
As have mentioned, I could sucessfully build libpinyin after commented the code.

**Comment by epico** [comment]
Right, it is required by FreeBSD.
BTW, The macro is okay on Fedora 25.

Maybe try the latest upstream version: https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx.html

**Comment by Novite5** [comment]
After upgraded autoconf-archive to version 20160320 and above[https://answers.launchpad.net/~gnome3-team/+archive/ubuntu/gnome3-staging/+build/10988793](url)
problem solved.
