### ISSUE TITLE
potential buffer-overrun by fscanf()

### ISSUE THREAD

**Issue by KazuhikoMaekawa** [libpinyin/libpinyin#69]
Actually these fscanf functions won't make malformed actions since these functions read only internal given tables. But fscanf() has incorrect format string in the following source files. When array size is 
defined with n, fscanf() format should have %(n-1)s. The following fscanf uses same number with 
defined array size.

1.  src/storage/chewing_large_table.cpp : line 671
 > int num = fscanf(infile, "%256s %256s %u %ld",

2.   src/storage/phrase_index.cpp : line 529
  > int num = fscanf(infile, "%256s %256s %u %ld",

3.  src/storage/phrase_large_table2.cpp : line 475
  > int num = fscanf(infile, "%256s %256s %u %ld",

4.  src/storage/table_info.cpp: line 198
  > num = fscanf(input, "source table format:%256s", str);

5.  src/storage/table_info.cpp: line 218
  > num = fscanf(input, "%256s %256s %256s %256s %256s %256s\n",

6. utils/storage/gen_pinyin_table.cpp: line 145
  > int num = fscanf(infile, "%1024s %1024s %u",

**Comment by epico** [comment]
Sorry, I am busy with some tasks, will fix this later.

**Comment by epico** [comment]
Sorry for late reply.

Fixed in https://github.com/epico/libpinyin/commit/ff713df50634fd5a2d3e5fd64fe5c57eb45b2b7a .
