### ISSUE TITLE
support Taiwanese pronunciations

### ISSUE THREAD

**Issue by heycam** [libpinyin/libpinyin#70]
It would be great if libpinyin could optionally support Taiwanese pronunciations, for example I want to type "lese" rather than "laji" for "垃圾".  I don't know whether the data sources you are using make this easy.

**Comment by epico** [comment]
Please try libzhuyin and ibus-libzhuyin, thanks!

URL: https://github.com/libzhuyin/

**Comment by heycam** [comment]
I wish I knew how to type zhuyin but unfortunately I don't. :-)  Maybe we could convert the zhuyin data to pinyin for this?

**Comment by epico** [comment]
Actually ibus-libzhuyin support pinyin with tone.

Please change the "Keyboard Layout" to "Hanyu Pinyin".

**Comment by jadahl** [comment]
Does ibus-libzhuyin support pinyin without tones?

Is there a way to have both Pinyin and Zhuyin as selectable input methods without having to go into settings and changing the layout? I can do this on Android (switch between pinyin, bopomofo, etc easily) and I'd like to be able to do this using ibus too (via GNOME).

**Comment by epico** [comment]
No, ibus-libzhuyin have to input pinyin with tone.

Maybe we can let ibus-libzhuyin input pinyin without tone.
Is this okay for you?

**Comment by jadahl** [comment]
> Maybe we can let ibus-libzhuyin input pinyin without tone.
Is this okay for you?

Personally, that'd be a improvement regarding pinyin input.

From a discoverability perspective changing it to be a separate input method would be another improvement however, so that a user coming from for example Fedora/RHEL using GNOME can immediately find "Pinyin", instead having to google and find this issue in order to configure the input method.

**Comment by epico** [comment]
Sorry, I understand your question now. ;)

There are "Intelligent Pinyin" and "Bopomofo" in ibus-libpinyin already.

Please just add "Bopomofo" engine.

I may not change ibus-libzhuyin for now.

**Comment by ping-wu** [comment]
I think the most important priority right now should be to add a decent database. 

I am running Fedora 27, and, compared to my previous experience, ibus-libpinyin has indeed improved greatly.  But occasionally I still had to flip several pages to find the word I want.

BTW, I recently found out that I couldn't type the word "註“ ("zhu") using ibus-libpinyin.  Is there any way to add words to the database?

**Comment by epico** [comment]
ibus-libpinyin allows to import third party dictionary in setup dialog.

**Comment by ping-wu** [comment]
How & which one?

**Comment by epico** [comment]
Launch "Intelligent Pinyin" setup dialog, in the page of "User data",
click the "Import" button to import some dictionary file.

The dictionary format is described in the help section of the page.

**Comment by ping-wu** [comment]
I have asked the same question before, but always received the same response.  Not too much help obviously.

This is just like someone asks the question of "how do I get from Beijing to Tianjin"? "Take the high speed train".

Correct answer of course, but I already know it.  The gist of the question of "how" was never answered.  Nor did it offer any substantive help.  A simple map showing the train station location will make a whole  lot of difference!

The help file in ibus-libpinyin is almost non-existent and archaic.  If the ibus-libpinyin developers are trying to force potential users to dig deep into the source code, they have succeed.  But not everyone has the time or desire to do so.

I will really appreciate it if you or any other ibus-libpinyin developer could kindly ask yourself the following question:

Suppose you are a Linux desktop user who has a need to produce Chinese documents on a regular basis.  Short of using the (very unstable in Linux but with an excellent set of dictionaries) Sogou (搜狗) under fcitx, how would you do about selecting and importing one of dictionaries from Sogou?

Of course this is a volunteers-driven open-source project, you don't have to answer my question, nor do you have do anything you don't feel like doing.  But just don't give me the bs.

**Comment by ping-wu** [comment]
heycam said:

> It would be great if libpinyin could optionally support Taiwanese pronunciations, for example I want to type "lese" rather than "laji" for "垃圾". I don't know whether the data sources you are using make this easy.
 
"Theoretically" this should be easily done.  You just type out a file which contains the following line:

垃圾 le'se

then import this file into ibus-libpinyin.

However, there currently appears to be a bug; after importing the above file, I typed "lese", there is still no "垃圾" in the list of candidates.

**Comment by epico** [comment]
ibus-libzhuyin 1.9.0 supports to input pinyin without tone, and ibus-libpinyin works with the above word now.

**Comment by heycam** [comment]
Great, thank you!

**Comment by epico** [comment]
Welcome!
