### ISSUE TITLE
configure.ac: AX_CXX_COMPILE_STDCXX(11) is wrong

### ISSUE THREAD

**Issue by xhebox** [libpinyin/libpinyin#72]
```
 sed -i 's/AX_CXX_COMPILE_STDCXX(11)/AX_CXX_COMPILE_STDCXX_11()/' configure
```
from [archlinux](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/libpinyin); correct macro from [gnu](https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx_11.html)

or correct usage from [glib](https://mail.gnome.org/archives/commits-list/2016-January/msg00668.html):
```
AX_CXX_COMPILE_STDCXX([11], [noext], [mandatory])
```

竟然一直没人报这个bug...

**Comment by epico** [comment]
Please update the autoconf-archive package.

See #68.

**Comment by xhebox** [comment]
@epico Just a comment, my issue is solved. I just recommend you to replace it with a portable way, but it's ok if you prefer using autoconf-archive:

Actually i have not installed autoconf-archive package. It seems that the only macro from autoconf-archive is this one(build was not broke by missing autoconf-archive except this macro).

Why not use the original method of autoconf, so we can throw the dependence of autoconf-archive? It's not worth adding a dependence for only one macro both in my view of packaging distro and writing a software(this dependence is not installed by default on a lot of distros, such as gentoo, arch).

**Comment by epico** [comment]
Please read the content of AX_CXX_COMPILE_STDCXX_11 macro.

It still needs to use the AX_CXX_COMPILE_STDCXX macro.

**Comment by xhebox** [comment]
@epico Yes, you didn't get my idea clearly. It should be `AX_CXX_COMPILE_STDCXX([11], [noext], [mandatory])` without autoconf-archive, **this macro exists in the native autoconf even without autoconf-archive. But autoconf-archive packed the macro so that you can invoke the macro with only one parameter instead of three parameters**. Why not add the other two parameters so that we can throw the autoconf-archive away?

**Comment by epico** [comment]
Fixed in https://github.com/epico/libpinyin .

I just import the AX_CXX_COMPILE_STDCXX macro into git repo.

**Comment by xhebox** [comment]
nice job! :+1:
