### ISSUE TITLE
user_phrase_index.bin and user_pinyin_index.bin were cleared after switching from bdb to kyotocabinet

### ISSUE THREAD

**Issue by felixonmars** [libpinyin/libpinyin#74]
I have a quick look of the code, and it seems these two main user phrase dbs are using FacadePhraseTable3. After switching from berkeley db to kyoto cabinet, the two files were cleared an all user generated phrases were lost. The tool bdbtokyotodb doesn't seem to work on these two files but only user_bigram.db, which I have tried to convert but doesn't seem to make a difference. Any hints here?

**Comment by epico** [comment]
libpinyin will clear data when update.

I suggest to clear user data when upgrading, or some difficult bugs will appear.

**Comment by felixonmars** [comment]
I see. So is kyotodbtobdb still useful in the process?

**Comment by epico** [comment]
I think libpinyin will only clear data when needed, like file format or data changes.

kyotodbtobdb only works when no file format or data changes.

**Comment by epico** [comment]
I think libpinyin doesn't change during 1.9.92 -> 2.0.0.

But the kyotodbtobdb may be old, not able to handle the data file.

**Comment by epico** [comment]
I updated bdbtokyotodb, but without tests.
URL: https://pwu.fedorapeople.org/bdbtokyotodb/

**Comment by epico** [comment]
Close issue.
