### ISSUE TITLE
能否调整模糊拼音的出词“规则”？

### ISSUE THREAD

**Issue by cherrot** [libpinyin/libpinyin#76]
没找到有人提过相似问题。当输入模糊音（比如`xian`）时，我希望能够按照如下规则出词：
1. 优先匹配词组，比如`西安`，`锡安`等。
2. 如果用户没有明确输入切音符（单引号`'`），那么优先按照`xian`的发音出字
3. `xian`枚举完以后，再按`xi'an`出字，也就是先选`xi`，再选`an`

目前libpinyin满足1，但2和3是按照全局的词频出字的：

![image](https://user-images.githubusercontent.com/964629/28883473-315eb366-77e1-11e7-9a73-5ceaa31e2936.png)
![image](https://user-images.githubusercontent.com/964629/28883489-3f0a0010-77e1-11e7-997c-f441918b1cd8.png)

sogou是按照该规则出字的，让我可以比较容易的找到匹配`xian`的字（毕竟如果想直接找`xi` `an`我可以输入`xi'an`）：

![image](https://user-images.githubusercontent.com/964629/28883522-5a2a2d16-77e1-11e7-98f2-863e7286cec6.png)
![image](https://user-images.githubusercontent.com/964629/28883531-64efd37c-77e1-11e7-943c-e40b3605af72.png)
![image](https://user-images.githubusercontent.com/964629/28883558-79940bc2-77e1-11e7-9d52-c477b0dc0b5f.png)
（这是穷举完所有的`xian`后，自动调整为`xi'an`继续出字。

模糊音的可选项太多，很难快速找到自己想要输入的文字，我认为影响选词体验。所以能否更新出词规则，或提供选项设置该规则？感谢！

**Comment by epico** [comment]
"xian" 的候选字太多，如果用户想选择 "xi" 的话需要翻很多页。
iOS 好像也是只按照词频排序的，"xian" 和 "xi" 的结果混合在一起。
这样的话，可以不用输入 " ' ".

**Comment by ping-wu** [comment]
我打入xi'an，出来的就是西安，如附图：
![selection_089](https://user-images.githubusercontent.com/21325422/28907657-efc1db84-77ba-11e7-8262-113701ca929b.jpg)

註：我使用的是ibus-pinyin 而不是 ibus-libpinyin

**Comment by cherrot** [comment]
@epico 但我依然觉得这应该由用户来决定。 `xian`和`xi`的候选字都太多，如果想快速输入`xi`，显式的输入`xi'an`并不是很难培养的习惯。

@ping-wu  没错，在我陈述的规则里，libpinyin满足1. 但不满足2和3，我觉得2和3比较影响使用体验。

**Comment by epico** [comment]
也许可以给 ibus-libpinyin 添加个选项。。。

**Comment by cherrot** [comment]
那`fcitx-libpinyin`也可以受益吗？

**Comment by epico** [comment]
应该可以，但是需要修改代码。。。

我先看看如何在 libpinyin 中实现。。。

**Comment by epico** [comment]
此特性已进入 https://github.com/epico/libpinyin/ .

方便的话，请给 fcitx-libpinyin 开 issue, 更新 pinyin_guess_candidates 的使用。

**Comment by cherrot** [comment]
https://github.com/epico/libpinyin/commit/bc600e1d24e543c82bb6acf35d2195d50dbf5495 ?

**Comment by epico** [comment]
Yes.

**Comment by epico** [comment]
As libpinyin 2.1.91 is released, close issue.
