### ISSUE TITLE
是否有适合ibus-libpinyin的词汇？

### ISSUE THREAD

**Issue by ping-wu** [libpinyin/libpinyin#77]
如题。

我使用ibus-pinyin时，可以利用一个 pinyin-database (SQLite），非常顺。

如何将这个词汇转成可以让ibus-libpinyin使用？

**Comment by epico** [comment]
ibus-libpinyin 可以导入文本格式的词库，在 “首选项” 对话框的 “用户数据” 页面，
文本词库格式在下方有说明。

**Comment by ping-wu** [comment]
ibus-libpinyin里，提供了一套不同领域的字典，让使用者选择：

​不过我打勾以后，发现并没有任何改变。

是否这只是为以后的功能，预留的namespace?

**Comment by epico** [comment]
其实那些词库是算法生成的，词汇量很小。

**Comment by ping-wu** [comment]
装设Fedora以后，在 ~/.cache/ibus/libpinyin 会产生一个 user_bigram.db 这个档案，超过 6M bytes。
很显然，这就是ibus-libpinyin使用者自己创造出来的词汇。

不过为什么一下子就会跳到6M呢？ Google不出来对这个档案的解释。
另外，使用一阵子以后，能不能把它放到/usr/share . . . 里？

**Comment by epico** [comment]
那个文件是 Kyoto Cabinet 格式的，好像是 Kyoto Cabinet 默认大小，不影响使用的。

/usr/share 是只读的，而且是多用户共享的，无法放入。

**Comment by ping-wu** [comment]
ibus-libpinyin 的词汇，跟ibus-pinyin比起来，实在差太多了。因为这个缘故，ibus-pinyin好用多了。

不过这个说法，只是在Ubuntu里有效。Fedora的套件库里，没有pinyin-database这个套件，因此两者都是很awkward的中文输入引擎。

**Comment by epico** [comment]
libpinyin 在 Ubuntu 的版本太低了。

**Comment by epico** [comment]
词库是有版权的，用户可以选择自己喜欢的输入法，有多个输入法也是好事。

**Comment by mzy2240** [comment]
不得不说 maintainer的态度是真的好 我有两个建议: 1. 能否由你们提供一个user导入的词库版本 2. 有的时候输入了英文之后才发现是在拼音模式下 按了shift又要重新再打 能否支持按了shift之后保留已打的内容 我知道可以按回车 但逻辑上按shift保留更自然 谢谢！ @epico

**Comment by epico** [comment]
1. 主要是版权的问题，如果有 GPLv3 和 ASL 2.0 兼容的词库，可以倒入 libpinyin; 网上的某些词库有版权问题，无法导入的。
2. 个人觉得 shift 和 enter, 有不同的功能，也可以。

**Comment by englianhu** [comment]
> 词库是有版权的，用户可以选择自己喜欢的输入法，有多个输入法也是好事。

《问百度》🎼
不晓得去哪儿找（或添加）词汇、术语等辞典呢？
