### ISSUE TITLE
Can I use libpinyin to get pinyin of Chinese words?

### ISSUE THREAD

**Issue by ksqsf** [libpinyin/libpinyin#78]
Like, convert 你好 to ni'hao. Is it possible with libpinyin?

**Comment by epico** [comment]
以下函数可以帮助查询汉字的拼音:
pinyin_lookup_tokens
pinyin_token_get_n_pronunciation
pinyin_token_get_nth_pronunciation
pinyin_get_pinyin_string
...

注意对于多音字，libpinyin 无法正确转换。

**Comment by ksqsf** [comment]
Thanks for your kind reply.
