### ISSUE TITLE
麻烦修正一下“给水”的读音

### ISSUE THREAD

**Issue by hillwoodroc** [libpinyin/libpinyin#79]
“给水”读作jǐshuǐ，不是gěishuǐ，libpinyin 的词库读音是错的。

**Comment by ping-wu** [comment]
先建立一个档案，包括下面一行：
. . .
给水  ji'shui

然后到 ibus-libpinyin -> preference -> import 

退出再进入 ibus-libpinyin，打入 jishui 后， “给水” 就会出现在选择栏。

**Comment by epico** [comment]
I will fix it in the next release.

**Comment by epico** [comment]
Fixed in model15.text.tar.gz .

**Comment by epico** [comment]
As libpinyin 2.1.91 is released, close issue.
