### ISSUE TITLE
请问如何用gdb分析libpinyin

### ISSUE THREAD

**Issue by qiangzhao** [libpinyin/libpinyin#80]
您好：

libpinyin在我的桌面有时崩溃，所以我希望使用gdb分析其崩溃原因。
但是libpinyin是由ibus->ibus-libpinyin->libpinyin调用运行的，所以事先无从知晓libpinyin的启动点；由于崩溃，亦不可知其pid；请问如何抓到这个进程？

另外，由于libpinyin是在同时按下"Compose key + Space key"，令输入法切换到指定输入引擎时启动的：有什么命令行的方法可以模拟libpinyin的这一启动过程吗？

**Comment by epico** [comment]
其实我是按照如下方法调试的:

1. 编译 ibus-libpinyin 的 git repo
2. kill 所有的 /usr/libexec/ibus-engine-libpinyin 进程
3. 用 gdb 打开 git repo 中的 ibus-engine-libpinyin 程序
4. 在 gdb 中，启动 ibus-engine-libpinyin 并带有 "--ibus" 参数
5. 切换到 "Intelligent Pinyin" 即可开始调试

顺便说一句，在 Fedora 中，有 gnome-abrt 捕捉崩溃比较容易。

**Comment by qiangzhao** [comment]
十分感谢，我准备按照这个方法尝试一下
