### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by bdfish** [libpinyin/libpinyin#81]
[log.txt](https://github.com/libpinyin/libpinyin/files/1577861/log.txt)

compile in debian9.3(64bit) stable(clean install in VM)

**Comment by epico** [comment]
Please install glib 2.0 dev package in Debian.

**Comment by bdfish** [comment]
![screenshot from 2017-12-21 12-59-42](https://user-images.githubusercontent.com/15389690/34241208-d464837a-e64e-11e7-96b8-6b5466ebd05b.png)

**Comment by epico** [comment]
Please check whether the file exists?
//lib/x86_64-linux-gnu/libglib-2.0.so.0

**Comment by bdfish** [comment]
![screenshot from 2017-12-21 13-40-31](https://user-images.githubusercontent.com/15389690/34242068-8b11e022-e654-11e7-8fe0-3aa134d6b29e.png)

**Comment by bdfish** [comment]
By the way,i just download libpinyin and ibus-libpinyin latest deb from debian website,everything goes well,but it hard to understand why i can not compile it in same version of them.

Here is the link,unfortunately,all of libpinyin components are in debian experimental repo.
(https://packages.debian.org/search?searchon=names&keywords=libpinyin)

**Comment by epico** [comment]
What is the output of `ls -lh libglib-2.0.so.0`?

**Comment by bdfish** [comment]
![screenshot from 2017-12-21 13-53-18](https://user-images.githubusercontent.com/15389690/34242412-51673758-e656-11e7-86fa-4201c612fd27.png)

**Comment by epico** [comment]
source deb package compile okay?

**Comment by bdfish** [comment]
I compile it just know,no error occur,it seems the maintainer had a patch on it.

Patch info?I'm not sure
[0001-Add-missing-LDADD.patch.txt](https://github.com/libpinyin/libpinyin/files/1578106/0001-Add-missing-LDADD.patch.txt)

Where to download
[https://packages.debian.org/experimental/libpinyin13](url)

**Comment by epico** [comment]
Please try the above Debian patch.

**Comment by bdfish** [comment]
Well,i got it.
