### ISSUE TITLE
可以删除词库吗

### ISSUE THREAD

**Issue by Nif1heim** [libpinyin/libpinyin#84]
有时候不小心打错了一个词，然后就删不掉了。

**Comment by epico** [comment]
请问选项“将每个输入记录为新的词汇”是否打开？

**Comment by Nif1heim** [comment]
打开了

**Comment by epico** [comment]
应该移动到该候选词，按 Ctrl + Shift + D 即可。

另外，在设置对话框中，可以导出词汇；删除不想要的词汇后，点击清除数据按钮，再将用户数据重新导入即可。

**Comment by Nif1heim** [comment]
好的，谢谢！
