### ISSUE TITLE
请求增加新功能！The request for new abilities!

### ISSUE THREAD

**Issue by Ex-mortal** [libpinyin/libpinyin#89]
(Rolling down for English)
0，一个问题：双拼输入法中，以元音开头（a, e, o）的单个字母无法成词。（即：输入 e 后，候选词立列表中只有英文，并无中文。）
1，希望支持固顶词。选词的效率太低，固定的词序可以极大增加打字效率。目前我是用fcitx自带的拼音增强功能插件实现的这个功能，而 ibus 输入法中则没有这个组件。但 fcitx 的插件也并不完美，因为它无法在平时输入的过程中，让用户自行调整词序，或者增删词条。我希望 libpinyin 本身支持这个功能。
2，希望支持辅助码。拥有辅助码的双拼才是真正的双拼。全拼也可以用这个功能增加选字效率（例：搜狗拼音可以使用 Tab + 笔画检字）。Windows 系统中辅助码做的最好的是拼音加加，它提供两种使用辅助码的形式：直接辅助码，以及间接辅助码。a) 直接辅助码：只适用于双拼，在输入一个词或句子的完整拼音之后，直接键入一位字母进行检索。b) 间接辅助码：适用于双拼以及全拼，输入拼音之后，按下 Tab 键，再用辅助码进行检字。双拼一般使用两个字母的形码作为辅助码，但事实上辅助码可以是不限长度的任意一种码表，例如笔画码。
3,以词定字。这是提升打字效率的另一种方法：输入词组的拼音，然后按下“[”或“]”选择第一个字或者最后一个字（例：“邋遢”这个词中的任意一个字）。Fcitx 提供了这个功能，而 ibus 没有提供。 我希望 libpinyin 支持这个功能。
4，希望可以增加的按键选项：a) shift 在切换英文的同时，将已经输入的编码上屏。b) Tab / Shift + Tab 上下翻页。c) 自定义快捷键功能。
5，双拼方案自定义。虽然我现在用的小鹤双拼已经有了支持，但还有许多人在用各种稀奇古怪的自定义双拼。增加这个功能会让这个输入法更牛。
6，希望支持注音输入法的许氏键盘，以及其他类似的注音输入法三拼方案。理由同上一条，虽然我用不到，但是这样会让这个输入法更灵活，看起来更牛。
7，对各种云拼音的支持。

-----
0. A problem: it can not compose a chinese character with double pinyin when a single a, e, or o is input. (i.e. Candidates appear in english in this case.)
1. In need of supporting fixed word order. Lacking efficiency as words selection of pinyin input method, a fixed order of several words at the initial of candidates surely could be an enhancement. I am using an default addon of fcitx to obtain the function, which is absence in ibus. But I whish Libpinyin could achieve the function itself.
2. In need of supporting auxiliary code table. A double pinyin scheme is not a ture double pinyin scheme without auxiliaries. And general pinyin could also get benifit from it (e.g. Sogou Pinyin offered a retrieval of tapping stroke codes after Tab key). The best achievement of auxiliaries on Windows is from Pinyin Plu Plus, offering two forms of it: a) direct auxiliaries, which is only utilized with double pinyin, to retrieve a word or sentence by a single letter after the fully inputing of pinyin. b) indirect auxiliaries, sutable for all kinds of pinyin, to retrieve after a tappping Tab by letters, usually two in number on double pinyin, but could be in any length actually, and in any forms of codes talbes (e.g. strokes).
3. Confirming by words is in want. To select the initial or final character of a word by [ and ].(e.g. any character in 邋遢.)
4. Key bindings that are in want: a) Shift for sending input codes as soon as changing IM state to English. b) Tab / Shift + Tab for page up / down. c) Customization of key bindings.
5. The want of double pinyin customization. Although my theme is supported very well, others might use a minority of schemes. This support could improve the IM's flexibility, and niubility.
6. The want of Bopomofo Xu's keyboard, for its niubility.
7. The support of cloud pinyin is also in want.

**Comment by epico** [comment]
请分开汇报问题，谢谢！
