### ISSUE TITLE
sporadic build failures (illegal instruction)

### ISSUE THREAD

**Issue by abderrahim** [libpinyin/libpinyin#95]
I often see this failure
```
Making all in data
make[2]: Entering directory '/buildstream/gnome/core-deps/libpinyin.bst/data'
rm -f phrase_index.bin pinyin_index.bin addon_phrase_index.bin addon_pinyin_index.bin bigram.db gb_char.bin gbk_char.bin opengram.bin merged.bin art.bin culture.bin economy.bin geology.bin history.bin life.bin nature.bin people.bin science.bin society.bin sport.bin technology.bin
../utils/storage/gen_binary_files --table-dir ../data
../utils/storage/import_interpolation --table-dir ../data < ../data/interpolation2.text
/bin/sh: line 1:  3688 Illegal instruction     (core dumped) ../utils/storage/import_interpolation --table-dir ../data < ../data/interpolation2.text
make[2]: *** [Makefile:540: bigram.db] Error 132
make[2]: Leaving directory '/buildstream/gnome/core-deps/libpinyin.bst/data'
make[1]: *** [Makefile:477: all-recursive] Error 1
make[1]: Leaving directory '/buildstream/gnome/core-deps/libpinyin.bst'
make: *** [Makefile:382: all] Error 2
```

At first I thought that import_interpolation is being called before it was compiled (or while it was being compiled), but even with `-j1` it sometimes happen.

The full build log is here: [cd1940de-build.5110.log](https://github.com/libpinyin/libpinyin/files/2487803/cd1940de-build.5110.log)

**Comment by abderrahim** [comment]
Sorry, I forgot to mention that. This is happening as part of the GNOME integration pipeline https://gitlab.gnome.org/GNOME/gnome-build-meta, we are using [BuildStream](https://buildstream.build/) to build in a sandbox.

The fact is it doesn't happen every time, so I'm not sure how to reproduce it.

**Comment by epico** [comment]
Does this failure still happens with current 2.2.x series?

**Comment by abderrahim** [comment]
Yes, it happened with 2.2.1.

BTW, I see cmake build files in the repository. We could try to use that, but they are not in the release tarballs.

**Comment by epico** [comment]
Sorry, cmake build files may be out-of-date sometimes.

Usually we will keep autoconf files updated.

**Comment by epico** [comment]
Could you check again with libpinyin 2.4.92?

**Comment by epico** [comment]
No response, close issue.
