### ISSUE TITLE
zhoumo doesn't suggest 週末

### ISSUE THREAD

**Issue by marmistrz** [libpinyin/libpinyin#96]
I'm learning Chinese, so I may have something wrong, but looking at what the Chinese translation of Android does, the Taiwanese standard for weekdays 週五, not 周五, etc.

libpinyin doesn't suggest the former at all while typing zhoumo. (at least, it's not suggested through ibus-libpinyin)

**Comment by marmistrz** [comment]
@epico I don't know zhuyin. In the western countries pinyin is usually taught, so needing to use zhuyin is an extra learning curve. 
Does ibus-libpinyin use libpinyin directly to provide TC suggestions or does it go through e.g. opencc to convert from SC to TC?

**Comment by epico** [comment]
ibus-libpinyin just convert from SC to TC.

In ibus-libzhuyin, there is pinyin support, but it need to input pinyin with pinyin tone.

**Comment by marmistrz** [comment]
OpenCC handles ‘周末’ correctly but for some reason `ibus-libpinyin` in Arch Linux doesn't build against OpenCC:

```
In [2]: OpenCC('s2tw').convert('周末')                                                                                                                
Out[2]: '週末'

In [3]: OpenCC('s2t').convert('周末')                                                                                                                 
Out[3]: '週末'
```

**Comment by epico** [comment]
Maybe you could ask ArchLinux to enable opencc.

In the past, some one complained about opencc conversion, ibus-libpinyin currently disable opencc usage by default.

**Comment by epico** [comment]
As libpinyin 2.2.2 and ibus-libpinyin 1.11.0 are released, close issue.
