### ISSUE TITLE
Extract pinyin->character mapping?

### ISSUE THREAD

**Issue by girzel** [libpinyin/libpinyin#98]
I'm looking to update Emacs' pinyin-to-character mapping, and since libpinyin has a friendly license, I'm wondering if we can use your mapping. Is there any way to extract a simple text map from this project, so that we could build an association list that looks like "zhong' -> "中种重众终钟忠衷肿仲锺踵盅冢忪舯螽"?

What I'd like to do is make an Emacs input method that uses libpinyin directly, but one thing at a time...

**Comment by epico** [comment]
Please check https://sourceforge.net/projects/libpinyin/files/models/ .

**Comment by girzel** [comment]
Perfect, thank you.

**Comment by epico** [comment]
Welcome
